In [1]:
#Numpy Arrays
#Numpy has many built in functions and capabilities.The most important of Numpy: vectors,arrays,matrices and number generation.
#Numpy arrays come in two flavors vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d arrays(but you should note a matrix can have only one row or column)


[1, 2, 3, 4, 5, 6, -89, -96, 77, 56, -25, 0, -12, 23]
<class 'list'>


In [2]:
l=[1,2,3,4,5,6,-600,-95,-89,0,-56,90,4]
print(l)

[1, 2, 3, 4, 5, 6, -600, -95, -89, 0, -56, 90, 4]


In [3]:
import numpy as np
l=[1,2,3,4,5,6,-600,-95,-89,0,-56,90,4]
z=np.array(l)
print(z)
print(type(z))

[   1    2    3    4    5    6 -600  -95  -89    0  -56   90    4]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
l=[1,22,33,44,55,66,-89,"Alex","William",45]
print(l)
z=np.array(l)
print(z)
print(type(z))

[1, 22, 33, 44, 55, 66, -89, 'Alex', 'William', 45]
['1' '22' '33' '44' '55' '66' '-89' 'Alex' 'William' '45']
<class 'numpy.ndarray'>


In [10]:
import numpy as np
x = np.arange(0,31)
x
print(x[0])#first index
print(len(x))
print(x[2:6:])
print(x[-1:])#last index return
print(x[-2])#second last index return
print(x[:-2])#excluded last index and returns the rest all
print(x[::])#full list..==x
print(x[::-1])#reverse list....from the last
print(x[::1])#from the beginning..
print(x[::-2])# take 2 interval from the end and print reverse order...
print(x[:3:-1])#upto 3 index remove and rest will print in reverse

0
31
[2 3 4 5]
[30]
29
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4  3  2  1  0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[30 28 26 24 22 20 18 16 14 12 10  8  6  4  2  0]
[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4]


In [8]:
# List.
import numpy as np
my_list=[1,2,3,4,5,6,-89,-96,77,56,-25,0,-12,23]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5, 6, -89, -96, 77, 56, -25, 0, -12, 23]
<class 'list'>


In [12]:
import numpy as np
#2D lists
my_matrix=[[11,12,13],[14,15,16],[17,18,19]]
print(np.array(my_matrix))

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [15]:
import numpy as np
#2D lists
z=[[10,23,56,89],[40,50,60,47],[7,89,52,45],[12,36,56,78],[56,46,89,23],[23,45,56,78]]
print(np.array(z))

[[10 23 56 89]
 [40 50 60 47]
 [ 7 89 52 45]
 [12 36 56 78]
 [56 46 89 23]
 [23 45 56 78]]


In [18]:
#There are many ways to generate arrays.
#arange: return evenly spaced values within a given interval
import numpy as np
#arange(start,stop,step)
arr=np.arange(2,60,2)#n-1 index
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58]


In [19]:
import numpy as np
v=np.arange(1,60,2)
print(v)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59]


In [28]:
import numpy as np
l=[]
for x in np.arange(1,51):
    if(x%5==0):
        print(x,end=',')
        l.append(x)
print(l)

5,10,15,20,25,30,35,40,45,50,[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [34]:
import numpy as np
# advanced comphrension list generator
for x in np.arange(1,51):
    if(x%5==0):
        print(x,end=',')
        

5,10,15,20,25,30,35,40,45,50,

In [35]:
a=[]
[a.append(x) for x in np.arange(1,51) if (x%2==0 and x%5==0)]
print(a)

[10, 20, 30, 40, 50]


In [1]:
l=[12,56,89,23,50,14,25,36,78,91,2,3,4,6,5,7,12]
Evenlist=list(filter(lambda x:(x%2==0),l))
print(Evenlist)

[12, 56, 50, 14, 36, 78, 2, 4, 6, 12]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
