## The Basics

In [15]:
import numpy as np
a = np.array([1,2,3,4],dtype="int16")
print(a)

[1 2 3 4]


In [3]:
b=np.array([[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9]])
print(b)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [5]:
# Get dimension
a.ndim
b.ndim

2

In [6]:
# Get shape (vector so only one dimsion)
b.shape

(3, 3)

In [13]:
# Get type
a.dtype

dtype('int16')

In [17]:
# Get size 
a.itemsize

2

In [19]:
# Total size
a.size*a.itemsize

8

In [20]:
a.nbytes

8

In [22]:
# Get specific element[r,c]
b[0,2]

0.3

In [23]:
# Get specific row 
b[0,:]

array([0.1, 0.2, 0.3])

In [27]:
# Get a specific column
b[:,1]

array([0.2, 0.5, 0.8])

In [30]:
#Getting a little more fancy[startindex:endindex:stepsize]


In [29]:
# 3-d example
import numpy as np
k=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(k)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
# Get specific element (outside in)
k[0,1,1]
k[1,1,1]

8